"""Decode live HID reports with a mapping generated by collect_gamepad_hid_mapping.py."""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sim.gamepad_hid_mapping import decode_report_dict, load_mapping


READ_SIZE = 128


def main() -> int:
    args = _parse_args()
    mapping = load_mapping(Path(args.mapping))

    try:
        import hid
    except ImportError:
        print("hidapi is not installed in this environment.")
        return 2

    devices = list(hid.enumerate())
    selected = _select_device(devices, mapping, args.device_index)
    if selected is None:
        return 1

    dev = hid.device()
    try:
        dev.open_path(selected["path"])
    except Exception as exc:
        print(f"Failed to open HID device: {exc}")
        return 1

    print("Decoding live reports. Ctrl+C to stop.")
    last_line = ""
    try:
        while True:
            data = dev.read(READ_SIZE, timeout_ms=args.timeout_ms)
            if not data:
                continue
            raw = bytes(data)
            try:
                decoded = decode_report_dict(raw, mapping, deadzone=args.deadzone)
            except ValueError:
                continue
            line = _format_decoded(decoded)
            if line != last_line:
                last_line = line
                print(line, flush=True)
            time.sleep(args.sleep)
    except KeyboardInterrupt:
        print("\nStopped.")
        return 0
    finally:
        try:
            dev.close()
        except Exception:
            pass


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mapping", required=True, help="Mapping JSON generated by collect_gamepad_hid_mapping.py.")
    parser.add_argument("--device-index", type=int, help="Force HID device index instead of matching mapping device IDs.")
    parser.add_argument("--timeout-ms", type=int, default=20)
    parser.add_argument("--deadzone", type=float, default=0.10)
    parser.add_argument("--sleep", type=float, default=0.01)
    return parser.parse_args()


def _select_device(
    devices: list[dict[str, Any]],
    mapping: dict[str, Any],
    device_index: int | None,
) -> dict[str, Any] | None:
    if device_index is not None:
        if device_index < 0 or device_index >= len(devices):
            print(f"Invalid --device-index {device_index}")
            return None
        return devices[device_index]

    device_cfg = mapping.get("device", {})
    vendor_id = device_cfg.get("vendor_id")
    product_id = device_cfg.get("product_id")
    if vendor_id is not None and product_id is not None:
        for info in devices:
            if info.get("vendor_id") == vendor_id and info.get("product_id") == product_id:
                return info

    for idx, info in enumerate(devices):
        print(f"[{idx:02d}] vid=0x{int(info.get('vendor_id') or 0):04x} "
              f"pid=0x{int(info.get('product_id') or 0):04x} "
              f"{info.get('manufacturer_string') or '?'} / {info.get('product_string') or '?'}")
    choice = input("Device index: ").strip()
    try:
        selected = int(choice)
    except ValueError:
        print("Invalid device index.")
        return None
    if selected < 0 or selected >= len(devices):
        print("Invalid device index.")
        return None
    return devices[selected]


def _format_decoded(decoded: dict[str, Any]) -> str:
    buttons = decoded.get("buttons", {})
    pressed = ",".join(name for name, active in sorted(buttons.items()) if active) or "-"
    return (
        f"lx={decoded['left_x']:+.3f} "
        f"ly={decoded['left_y']:+.3f} "
        f"lt={decoded['lt']:.3f} "
        f"rt={decoded['rt']:.3f} "
        f"buttons={pressed}"
    )


if __name__ == "__main__":
    raise SystemExit(main())
